import { F13, F12, F11, F4 } from "../../Index";
const CardDB: any = {
  Hamburger: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham1",
      category: "Hamburgers",
      id: "H1H",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham2",
      category: "Hamburgers",
      id: "H2H",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham3",
      category: "Hamburgers",
      id: "H3H",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham4",
      category: "Hamburgers",
      id: "H4H",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham5",
      category: "Hamburgers",
      id: "H5H",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham6",
      category: "Hamburgers",
      id: "H6H",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham7",
      category: "Hamburgers",
      id: "H7H",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham8",
      category: "Hamburgers",
      id: "H8H",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham9",
      category: "Hamburgers",
      id: "H9H",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham10",
      category: "Hamburgers",
      id: "H10H",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham11",
      category: "Hamburgers",
      id: "H11H",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham12",
      category: "Hamburgers",
      id: "H12H",
    },
  ],
  Pizza: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza1",
      category: "Pizzas",
      id: "P1P",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza2",
      category: "Pizzas",
      id: "P2P",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza3",
      category: "Pizzas",
      id: "P3P",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza4",
      category: "Pizzas",
      id: "P4P",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza5",
      category: "Pizzas",
      id: "P5P",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza6",
      category: "Pizzas",
      id: "P6P",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza7",
      category: "Pizzas",
      id: "P7P",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza8",
      category: "Pizzas",
      id: "P8P",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza9",
      category: "Pizzas",
      id: "P9P",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza10",
      category: "Pizzas",
      id: "P10P",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza11",
      category: "Pizzas",
      id: "P11P",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza12",
      category: "Pizzas",
      id: "P12P",
    },
  ],
  Salad: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad1",
      category: "Salads",
      id: "S1S",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad2",
      category: "Salads",
      id: "S2S",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad3",
      category: "Salads",
      id: "S3S",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad4",
      category: "Salads",
      id: "S4S",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad5",
      category: "Salads",
      id: "S5S",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad6",
      category: "Salads",
      id: "S6S",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad7",
      category: "Salads",
      id: "S7S",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad8",
      category: "Salads",
      id: "S8S",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad9",
      category: "Salads",
      id: "S9S",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad10",
      category: "Salads",
      id: "S10S",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad11",
      category: "Salads",
      id: "S11S",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad12",
      category: "Salads",
      id: "S12S",
    },
  ],
  Chicken: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken1",
      category: "Chickens",
      id: "C1C",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken2",
      category: "Chickens",
      id: "C2C",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken3",
      category: "Chickens",
      id: "C3C",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken4",
      category: "Chickens",
      id: "C4C",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken5",
      category: "Chickens",
      id: "C5C",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken6",
      category: "Chickens",
      id: "C6C",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken7",
      category: "Chickens",
      id: "C7C",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken8",
      category: "Chickens",
      id: "C8C",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken9",
      category: "Chickens",
      id: "C9C",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken10",
      category: "Chickens",
      id: "C10C",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken11",
      category: "Chickens",
      id: "C11C",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken12",
      category: "Chickens",
      id: "C12C",
    },
  ],
  All: () => {
    let arr = [];
    for (let i = 0; i < 4; i++) {
      let [a, b, c] = [
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
        Math.floor(Math.random() * 10),
      ];
      let currObj: string = Object.keys(CardDB)[i];
      arr.push(CardDB[currObj][a], CardDB[currObj][b], CardDB[currObj][c]);
    }
    return arr;
  },
};
export default CardDB;
