import { F13, F12, F11, F4 } from "../../Index";
import { card_item, ItemDB } from "../../Components/Type/types";
const CardDB: ItemDB = {
  Hamburger: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham1",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham2",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham3",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham4",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham5",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham6",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham7",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham8",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham9",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham10",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham11",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham12",
      category: "Hamburgers",
      id: "string",
    },
  ],
  Pizza: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza1",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza2",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza3",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza4",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza5",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza6",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza7",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza8",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza9",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza10",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza11",
      category: "Pizzas",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F12,
      name: "Pizza12",
      category: "Pizzas",
      id: "string",
    },
  ],
  Salad: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad1",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad2",
      category: "Salads",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad3",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad4",
      category: "Salads",
      id: "string",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad5",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad6",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad7",
      category: "Salads",
      id: "string",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad8",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad9",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad10",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad11",
      category: "Salads",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad12",
      category: "Salads",
      id: "string",
    },
  ],
  Chicken: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken1",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken2",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken3",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken4",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 5.0,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken5",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken6",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken7",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 4.1,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken8",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.6,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken9",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken10",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken11",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken12",
      category: "Chickens",
      id: "string",
    },
  ],
  All: [
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham1",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham2",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F4,
      name: "Ham3",
      category: "Hamburgers",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad10",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad11",
      category: "Salads",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad12",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.8,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken10",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 4.0,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad1",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.5,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad2",
      category: "Salads",
      id: "string",
    },
    {
      rate: 2.3,
      price: 10,
      quantity: 1,
      image: F11,
      name: "Salad3",
      category: "Salads",
      id: "string",
    },
    {
      rate: 3.4,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken11",
      category: "Chickens",
      id: "string",
    },
    {
      rate: 4.3,
      price: 10,
      quantity: 1,
      image: F13,
      name: "Chicken12",
      category: "Chickens",
      id: "string",
    },
  ],
};

export default CardDB;
